jupyter-xeus/xeus-r

- src/xinterpreter.cpp
> define `ptr_R_WriteConsoleEx` so that R console output is propagated through `publish_stream()`

- src/xinterpreter.cpp
> only `publish_execution_result()` the last

- CMakeLists.txt
- environment-dev.yml
- include/xeus-r/rtools.hpp
- include/xeus-r/xinterpreter.hpp
- share/jupyter/kernels/xr/resources/execute.R
- share/jupyter/kernels/xr/resources/hello.R
- share/jupyter/kernels/xr/resources/setup.R
- src/routines.cpp
- src/xinterpreter.cpp
> Use `evaluate::evaluate()` 

- environment-dev.yml
- share/jupyter/kernels/xr/resources/configure.R
- share/jupyter/kernels/xr/resources/execute.R
- share/jupyter/kernels/xr/resources/init.R
- share/jupyter/kernels/xr/resources/routines.R
- share/jupyter/kernels/xr/resources/setup.R
- share/jupyter/kernels/xr/resources/utils.R
- src/routines.cpp
- src/xinterpreter.cpp
Again inspired from `IRkernel`, and using `repr` :
> handling plots

- share/jupyter/kernels/xr/resources/execute.R
> handle rlang::abort() errors specially

- .github/workflows/main.yml
> Disable CI on windows

- share/jupyter/kernels/xr/resources/routines.R
- src/routines.cpp
- src/xinterpreter.cpp
- test/test_xr_kernel.py
> Test `is_complete_request()`

- test/test_xr_kernel.py
> test error stream

- .gitignore
- share/jupyter/kernels/xr/resources/completion.R
- src/xinterpreter.cpp
- test/test_xr_kernel.py
closes #30 
This is a basic implementation, inspired from `IRkernel::completions()`
> Implement `complete_request_impl()`

- include/xeus-r/xinterpreter.hpp
- src/main.cpp
- src/xinterpreter.cpp
closes #39
This is an initial attempt, but this should rather go through the R history mechanism. I'll open an issue to deal with it properly down the road.
> attempt to honour store_history

- environment-dev.yml
- test/test_xr_kernel.py
> test ggplot2 again

- share/jupyter/kernels/xr/resources/execute.R
- share/jupyter/kernels/xr/resources/routines.R
- src/routines.cpp
- src/xinterpreter.cpp
- test/test_xr_kernel.py
> `execute()` R function don't always return success

- share/jupyter/kernels/xr/resources/routines.R
- test/test_xr_kernel.py
> implement `View()`

- share/jupyter/kernels/xr/resources/routines.R
> display html vignettes

- test/test_xr_kernel.py
> enable `test_execute_stderr`

- .github/workflows/main.yml
- CMakeLists.txt
- README.md
- environment-dev.yml
- environment-wasm-host.yml
- include/xeus-r/xinterpreter.hpp
- share/jupyter/kernels/xr/kernel.json.in
- src/main.cpp
- src/xinterpreter.cpp
- test/test_xr_kernel.py
- xeus-rConfig.cmake.in
> Update to xeus 5

- .github/workflows/main.yml
- docs/environment.yml
- docs/source/conf.py
- docs/source/dev-build-options.rst
- readthedocs.yml
> Attempt to fix docs

- CMakeLists.txt
> Fix windows tests

- CMakeLists.txt
- cmake/FindR.cmake
- include/xeus-r/xinterpreter.hpp
- share/jupyter/kernels/xr/kernel-win.json.in
- share/jupyter/kernels/xr/kernel.json.in
- src/main.cpp
- src/xinterpreter.cpp
- xeus-rConfig.cmake.in
> Address unused XEUS_R_EMSCRIPTEN_WASM_BUILD variable

- CMakeLists.txt
- share/jupyter/kernels/xr/resources/configure.R
- share/jupyter/kernels/xr/resources/setup.R
- share/jupyter/kernels/xr/resources/utils.R
- src/env_vars.js
- src/xinterpreter.cpp
There is no system `which` command in WebAssembly to retrieve the paths of files. This PR hard-codes the paths to what should be the default installation paths, but these may require some changes depending on how the virtual FS is organized.
> Fixes for xeus-r-lite

- .github/workflows/deploy-github-page.yml
This is due to https://github.com/jupyterlite/jupyterlite/issues/1402
> Fix missing content from the deployment

- CMakeLists.txt
- share/jupyter/kernels/xr/resources/configure.R
- Fix `Failed to find a library: libRlapack.so`
- Set png as default device
> Minor fixes for JupyterLite deployment

- cmake/FindR.cmake
So that it correctly sets `R_INCLUDE_DIR` and `R_LIBRARY_BASE` 
Factored out of #130: https://github.com/jupyter-xeus/xeus-r/pull/130#discussion_r1949059575
i.e. getting this locally: 
```
-- Configuring for non-Emscripten environment...
-- R_HOME           = /Users/romainfrancois/miniforge3/envs/xeusr2025/lib/R
-- R_INCLUDE_DIR    = /Users/romainfrancois/miniforge3/envs/xeusr2025/lib/R/include
-- R_LDFLAGS        = -fopenmp -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/romainfrancois/miniforge3/envs/xeusr2025/lib -L/Users/romainfrancois/miniforge3/envs/xeusr2025/lib -L/Users/romainfrancois/miniforge3/envs/xeusr2025/lib/R/lib -lR -L/Users/romainfrancois/miniforge3/envs/xeusr2025/lib -lpcre2-8 -ldeflate -llzma -lbz2 -lz -ldl -lm -liconv …
```
> update `FindR.cmake` script

- CMakeLists.txt
This cleans up small mistakes from #140
> Clean cross-compiling vars

- hera/R/routines.R
- hera/hera.Rproj
- src/routines.cpp
- src/xinterpreter.cpp
https://github.com/user-attachments/assets/5c5ca191-1809-47d7-9755-0f43bee148f8
> Support for `readline()`

- hera/R/comm.R
- hera/hera.Rproj
- src/routines.cpp
added for debugging when working on widgets, e.g. https://github.com/romainfrancois/wiipoc/pull/22
> + `CommManager$get_comm_info()`

- hera/R/execute.R
This fixes the error problem we chatted about this morning @SylvainCorlay 
(I need to improve the errors in `wiipoc` aka `jupyter.widgets.controls` but that is independent of this.
> hack no longer needed

- hera/R/execute.R
follow up to #149 for better error prints:
> `hera` no longer need `trim_rlang_error`

- src/xinterpreter.cpp
> Update file extension to include leading `.` prefix

- src/xinterpreter.cpp
I'm not sure this will fix the issue we discussed, but it might.
> fix protect dance in execute_request_impl
